.Dd $Mdocdate$
.Dt CHIP8 6
.Os
.Sh NAME
.Nm chip8
.Nd a simple CHIP-8 system emulator
.Sh SYNOPSIS
.Nm chip8
.Ar game
.Sh DESCRIPTION
The game
.Nm
plays a CHIP-8 ROM. It will appear in its own window.
.Sh SEE ALSO
.Xr intro 6
.Sh AUTHORS
This
.Nm
emulator implementation was written by Dylan Katz.
.Sh CAVEATS
This does not ship with any binaries. One may find them on the web.
